name: onepub
version: 2.0.3
homepage: https://onepub.dev
documentation: https://docs.onepub.dev
description: Command line tools for the OnePub private Dart/Flutter repository.
repository: https://github.com/onepub-dev/onepub
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  analyzer: 2.3.0
  args: 2.3.1
  async: 2.8.2
  basic_utils: 3.8.0
  cli_util: 0.3.5
  collection: 1.15.0
  crypto: 3.0.1
  dcli: 1.21.1
  dcli_core: 1.21.1
  equatable: 2.0.3
  frontend_server_client: 2.1.2
  glob: 2.0.1
  http: 0.13.3
  http_multi_server: 3.0.1
  http_parser: 4.0.0
  json_annotation: 4.1.0
  meta: 1.7.0
  oauth2: 2.0.0
  path: 1.8.1
  pedantic: 1.11.1
  pool: 1.5.0
  pub_semver: 2.1.0
  pubspec2: 2.4.1
  scope: 3.0.0
  settings_yaml: 3.4.2
  shelf: 1.2.0
  source_span: 1.8.1
  stack_trace: 1.10.0
  typed_data: 1.3.0
  url_builder: 1.0.0
  usage: 4.0.2
  validators2: 3.0.0
  watcher: 1.0.0
  win32: 2.0.5
  yaml: 3.1.0
  yaml_edit: 2.0.2
dev_dependencies: 
  lint_hard: ^2.0.0
  test: 1.17.12
executables: 
  onepub: 
  opub: 
platforms: 
  linux: 
  macos: 
  windows: 
false_secrets: 
  - lib/src/pub/validator/leak_detection.dart
